### ISSUE TITLE
npm testで一気に処理

### ISSUE THREAD

**Issue by cognitom** [miya0001/behat-wordpress#1]
@miya0001 しばらく前から、`phantomjs-prebuild`はPhantomJSの[起動完了を検知できる](https://github.com/Medium/phantomjs#running-with-webdriver)ようになりました。

今手動で、

```bash
$ npm start
$ npm test
$ npm stop
```

としているところは、

```bash
$ npm test
```

に一本化できそうです。
検証していないのですが、たぶんこんな感じのコードになるかと思います。

```javascript
const phantomjs = require('phantomjs-prebuilt')
const spawn = require('child_process').spawn
phantomjs.run(
  '--webdriver=4444',
  '--ignore-ssl-errors=yes',
  '--cookies-file=/tmp/webdriver_cookie.txt'
).then(program => {
  const behat = spawn('bin/behat')
  behat.stdout.pipe(process.stdout) // ログを標準出力にパイプ
  behat.on('exit', code => { program.kill() }) // behat終了時に、PhantomJSも終了
})
```

これを`npm test`で呼ぶようにすれば、OK。

**Comment by miya0001** [comment]
おお！これめちゃくちゃ気になってたんです！
さっそく試してみます！

**Comment by miya0001** [comment]
https://github.com/miya0001/phpcon2016-demo/commit/a6e727fa5dc4c8e07a0de9674c042c429e9416e1
